### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by bchandarr** [NBISweden/cytomine-bp-helm#32]
Hi, We are forking this repo and customising it for our deployment. 
Could you please let know if there are any licensing issue in doing so. 
Also could you please add a license to the repo.

**Comment by ahembal** [comment]
I hope the PR solved your issue. If not, we might need to discuss the situation with Cytomine main repository owners. For now, i will close the issue.

**Comment by bchandarr** [comment]
Thanks @ahembal, this solves the issue
